name: masjidi_io
description: "A new Flutter project."
version: 1.0.0+1

environment:
  sdk: ">=3.2.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  # Database
  supabase: ^2.0.9
  firebase: ^9.0.3
  # State Management
  mobx: ^2.3.3+2
  flutter_mobx: ^2.2.1+1
  flutter_riverpod: ^2.5.1
  hooks_riverpod: ^2.5.1
  riverpod_annotation: ^2.0.0
  flutter_hooks: ^0.20.5
  # UI / UX
  font_awesome_flutter: ^10.7.0
  google_fonts: ^4.0.4
  fluent_ui: ^4.8.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.1.4
  mobx_codegen: ^2.0.0+1
  riverpod_generator: ^2.4.0

flutter:
  uses-material-design: true
  assets:
    - assets/backgrounds/
  fonts:
    - family: MasjiIcon
      fonts:
        - asset: assets/fonts/MasjiIcon.ttf
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
