/// Flutter icons MasjiIcon
/// Copyright (C) 2024 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  MasjiIcon
///      fonts:
///       - asset: fonts/MasjiIcon.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class MasjiIcon {
  MasjiIcon._();

  static const _kFontFam = 'MasjiIcon';
  static const String? _kFontPkg = null;

  static const IconData logo = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
